### ISSUE TITLE
NFS doesn't work with the latest TrueNAS Scale API

### ISSUE THREAD

**Issue by tsuzu** [terricain/truenas-scale-csi#3]
## Expected
NFS works with the latest TrueNAS Scale (TrueNAS-22.12.4.2)

## What happened

I got an error like.
```
1208 18:34:15.683825       1 nfs.go:142] "failed to create NFS share" err="422 Unprocessable Entity" datasetName="main/nfs/nfs-pvc-2fa4b822-8af5-4ef2-89b3-bf30c1f838d8" mountpoint="/mnt/main/nfs/nfs-pvc-2fa4b822-8af5-4ef2-89b3-bf30c1f838d8"
```

I checked https://www.truenas.com/docs/api/scale_rest_api.html .
In the latest version of TrueNAS Scale, the result of `/sharing/nfs` has the `path` field instead of the `paths` field.

and so it fails to check and create a NFS share here.

https://github.com/terrycain/truenas-scale-csi/blob/116c0b7e84bdd9ed24582c26478fa11d3dd50414/pkg/driver/nfs.go#L123
https://github.com/terrycain/truenas-scale-csi/blob/116c0b7e84bdd9ed24582c26478fa11d3dd50414/pkg/driver/nfs.go#L132

Updating schema will resolve it, but lose compatibility with the old versions.

[democratic-csi](https://github.com/democratic-csi/democratic-csi) checks both of `path` and `paths`, so it's desired.

https://github.com/democratic-csi/democratic-csi/blob/79f16a0cf636f376f394f9b10084d949004b1e62/src/driver/freenas/api.js?plain=1#L357-L360

but i don't have a good idea to achieve it with the code generator

**Comment by terrycain** [comment]
oh the timing of this is perfect, I have literally just this minute updated to 23.10 so have yet to but will hit this myself 😆.

Will have a look at fixing this over the weekend

**Comment by tsuzu** [comment]
Wow! Really? I'm glad to hear that! 😄
Thank you for the wonderful project!

**Comment by terrycain** [comment]
New chart out 0.5.0, lemme know if you have any issues with it

**Comment by tsuzu** [comment]
I confirmed that v0.5.0 works well on my cluster.
Thank you so much for quick fix!

**Comment by terrycain** [comment]
Awesome glad it works for you :)
